### ISSUE TITLE
회원가입-인증번호 UX 수정 제안

### ISSUE THREAD

**Issue by rhrhak14** [boogle-lab/boogle-issue-board#10]
회원가입 시 메일 인증번호 전송 후 피드백
 - '인증번호 전송을 안내하는' 문구 혹은 해당 버튼 색상 수정 필요

**Comment by ywoo-park** [comment]
<img width="223" alt="인증01" src="https://user-images.githubusercontent.com/23696493/76700176-5871d880-66f8-11ea-8788-364a2879dda9.PNG">

**Comment by ywoo-park** [comment]
@rhrhak14 @hesed98 다음과 같이 수정했습니다! 피드백 해주시고 컨펌되었으면 issue close 부탁드릴게요~!

**Comment by rhrhak14** [comment]
확인했습니다ㅎㅎ!
