### ISSUE TITLE
판매자 전송 메일 문구 수정 제안

### ISSUE THREAD

**Issue by rhrhak14** [boogle-lab/boogle-issue-board#13]
북을박스 옵션 선택한 판매자 (메일 제목: 북을 박스 비치안내)에게 전송되는 이메일 문구 추가를 요청받았습니다!

디지털락 왼쪽 상단 램프가 깜빡이지 않는 박스를 사용하
실 수 있습니다. 사용 가능한 박스에 물품을 보관한 후 디지털락 '*' 버튼을 누르고 원하는 비밀번호 4자리를 설정한 후 '*' 버튼을 누르면 보관함이 잠깁니다. 디지털락 상단 램프에 파란색 등이 깜빡이는 것을 꼭 확인해주세요!

**Comment by ywoo-park** [comment]
@rhrhak14 메일을 확인하지 못하는 유저의 경우 마이페이지 내에서의 안내는 필요하지 않을까요?

**Comment by rhrhak14** [comment]
@ywoo21 동의합니다! 어떤 방식으로든, 북을 웹 내에서의 알림/안내가 구현되어야 할 것 같아요ㅠ! 내일 자세하게 논의해보아요..!

**Comment by ywoo-park** [comment]
@rhrhak14 네! 그러면 해당 이슈는 닫도록 하겠습니다:)
