### ISSUE TITLE
메인페이지 - 이벤트 문구 및 링크 수정 제안

### ISSUE THREAD

**Issue by rhrhak14** [boogle-lab/boogle-issue-board#16]
북을박스에 대한 문의가 많이 들어오는 관계로, 메인페이지에도 설명이 필요할 것 같다는 판단.
운영팀에서 다음과 같은 문구 및 링크를 제안.

문구:  '북을박스가 뭐야? / 궁금하면 / Click!'
링크: https://www.notion.so/boogle/3bbbb6ce5b554209ac14c900dba8ea88
![image](https://user-images.githubusercontent.com/41563796/76839484-e5dc3680-6878-11ea-9eec-9096c0da9e4f.png)

**Comment by rhrhak14** [comment]
@Yoojin-Kim @ywoo21 확인부탁드려요:-) 운영팀 요청사항입니다!

**Comment by ywoo-park** [comment]
@rhrhak14 확인했습니다!
