### ISSUE TITLE
[회원가입] 회원가입 통신 오류

### ISSUE THREAD

**Issue by wakii** [boogle-lab/boogle-issue-board#18]
![image](https://user-images.githubusercontent.com/17175936/76852305-5772af80-688e-11ea-83c6-45526634b9ad.png)

- 문제 : 네트워킹 오류 예상
- 해결 방법 : `가입완료` 버튼 이후 통신 코드를 바탕으로, 회원가입 실패 메세지 안내

**Comment by rhrhak14** [comment]
<해결방법>
- 회원가입 완료 페이지를 회원가입 실패 페이지로 안내
- 다음과 같은 문구
: 회원가입에 실패하였습니다. 다시 시도해주세요
 [다시 시도하기] 버튼
- 버튼 누르면 회원가입 초기 페이지로 이동
![image](https://user-images.githubusercontent.com/41563796/76853730-365f8e00-6891-11ea-9bcb-7be5c8a008f3.png)

**Comment by ywoo-park** [comment]
회원가입 통신 실패시 에러 문구가 뜨고 다시 회원가입 시작 페이지로 돌아가게 수정.
