### ISSUE TITLE
[회원가입] 학교 인증 이후, 가입완료 버튼 클릭 불가

### ISSUE THREAD

**Issue by wakii** [boogle-lab/boogle-issue-board#19]
![image](https://user-images.githubusercontent.com/17175936/76852592-07e0b380-688f-11ea-9272-64a4bf55c6e1.png)

- 원인 : ??
- 임시 해결 방법 : admin에서 회원가입 후 임시비밀번호 변경 안내
- 해결 방법 : 실패 메세지 안내

**Comment by rhrhak14** [comment]
<해결방법>
- 회원가입 완료 페이지를 회원가입 실패 페이지로 안내
- 다음과 같은 문구
: 회원가입에 실패하였습니다. 다시 시도해주세요
 [다시 시도하기] 버튼
- 버튼 누르면 회원가입 초기 페이지로 이동
![image](https://user-images.githubusercontent.com/41563796/76853730-365f8e00-6891-11ea-9bcb-7be5c8a008f3.png)

**Comment by ywoo-park** [comment]
실패 문구 구현 완료.
