### ISSUE TITLE
[거래프로세스] STEP 2->3 절차 개선

### ISSUE THREAD

**Issue by rhrhak14** [boogle-lab/boogle-issue-board#22]
**STEP 2 -> STEP 3**

**문제상황**
: 현재 '송금확인' 및 '투입확인'이 된 상태에서 운영팀이 <승인> 버튼을 눌러 스텝을 변경
: 구매자에게 '송금 확인 안내' 메일을 전송하기 위해서는 버튼이 두개로 나뉘어야함
 1. 송금확인 버튼을 눌렀을 시 : 구매자에게 확인 메일 전송
 2. 투입확인 버튼을 눌렀을 시 : 구매자에게 수령 메일 전송 (현재는 <승인> 버튼 클릭 시 이 메일만 전송) 

**해결방법**: 필드 추가 -> 대시보드 버튼 추가

cf) 송금 확인 버튼 누른 후 구매자에게 전송되는 메일 문구

**안녕하세요, 000님! 00책에 대한 입금 확인이 완료되었습니다. 지금부터 최대 48시간 이내에 북을박스에 책이 투입될 예정입니다.(주말 및 공휴일 제외)
판매자의 책 투입이 완료되면 박스번호와 비밀번호에 대한 안내 메일을 전송해드립니다.
북을박스는 베르크만스 우정원 2층 카페 그라찌에 옆에 위치해있습니다.
기타 문의사항은 카카오톡 플러스친구 '북을'을 통해 문의해주시기 바랍니다!
이용해주셔서 감사합니다.
캠퍼스 거래의 모든 것 - 북을**

만약 이름과 책제목 매칭이 어렵다면 첫문장은
'**안녕하세요 고객님! 구매 요청하신 책에 대한 입금 확인이 완료되었습니다.**' 로 수정

**Comment by ywoo-park** [comment]
테스트 진행후 정상적으로 작동하는 것 확인했습니다!
close하겠습니다!
