### ISSUE TITLE
[검색] 검색 오류 발생

### ISSUE THREAD

**Issue by rhrhak14** [boogle-lab/boogle-issue-board#24]
문제 상황: 특정 아이템이 검색 결과로 도출되지 않음
해결 방법: ??

**Comment by ywoo-park** [comment]
Principles of Economics
Economics(Global Edition)
경제학원론
마케팅원론

이것만 지금 안되는것으로 확인이 되었습니다

**Comment by ywoo-park** [comment]
@rhrhak14 해결했습니다!
DB에서 교수명/수업명 필드 추가 이후에 이전에 해당 필드가 없는 데이터들에 대해서 검색에 걸리지 않은 문제였습니다!
