### ISSUE TITLE
직거래 판매등록시 전송되는 메일 오류 수정

### ISSUE THREAD

**Issue by rhrhak14** [boogle-lab/boogle-issue-board#4]
- 직거래 판매등록 시 북을박스 비치 메일이 전송됨
- 아래와 같이 수정
1 직거래 판매자 판매 등록 - 전송되는 메일 X
2 직거래 구매자 구매선택 - 판매자에게 구매 요청 메일

**Comment by ywoo-park** [comment]
@rhrhak14 지우님 이렇게 항상 정리해주시면 될 것 같습니다:)

**Comment by ywoo-park** [comment]
@rhrhak14 직거래시에 판매 요청 메일만 가도록 수정 완료했습니다!
