### ISSUE TITLE
직거래 등록/구매신청 이후 마이페이지에서 '수령완료' 버튼 클릭 불가

### ISSUE THREAD

**Issue by wakii** [boogle-lab/boogle-issue-board#5]
- 직거래 구매신청 이후 `마이페이지` -> `구매현황` -> `거래상세보기` -> `거래중` 에서 `수령완료` 버튼 클릭 불가
- 직거래 등록 이후 마이페이지에서 '수령완료' 버튼 클릭 불가(과정 위와 동일)

<img width="294" alt="image" src="https://user-images.githubusercontent.com/17175936/76602331-08efa900-654e-11ea-8ec3-8eb38866c161.png">

- 다음과 같이 수정
1. 판매자 : `수령완료` 버튼을 `금액 수령완료`로 수정(제안) -> 버튼 클릭시 (판매자, 구매자에게 모두 )`거래완료` 로 상태 변경
2. 구매자 : `수령완료` 버튼을 `도서 수령완료`로 수정(제안) -> 버튼 클릭시 (판매자, 구매자에게 모두 )`거래완료` 로 상태 변경

-> 검토 후 영우님, 유진님에게 assign 부탁드려요!

**Comment by ywoo21** [comment]
![86171819-643B-4562-89F2-0A26445B24B3](https://user-images.githubusercontent.com/23696493/76610677-9e923500-655c-11ea-85a9-1226659b3669.png)

**Comment by yoojinkimm** [comment]
수정완료
