### ISSUE TITLE
판매자 본인 게시물에 대한 '구매하기' 버튼 수정 제안

### ISSUE THREAD

**Issue by wakii** [boogle-lab/boogle-issue-board#6]
![Image from iOS](https://user-images.githubusercontent.com/17175936/76602923-443ea780-654f-11ea-941a-315b726a5596.png)

- 판매자가 등록한 매물을 판매자 본인이 구매하기 신청이 가능함.

- 다음과 같이 수정 제안
1. `구매하기` 버튼 -> `수정하기` 또는 `삭제하기` 버튼 : 게시물 수정 및 삭제 기능 구현 필요

**Comment by ywoo-park** [comment]
![9A102328-D56E-4E6D-ADE0-314D081AFE4C](https://user-images.githubusercontent.com/23696493/76610754-be295d80-655c-11ea-9ed6-095361d384ba.png)

**Comment by ywoo-park** [comment]
@wakii 요구사항 대로 적용 했습니다!
