### ISSUE TITLE
판매자 정보 더보기 버튼 구현 미완

### ISSUE THREAD

**Issue by wakii** [boogle-lab/boogle-issue-board#7]
![Image from iOS](https://user-images.githubusercontent.com/17175936/76603123-bdd69580-654f-11ea-90a9-10db47dc1f06.png)

- 현재 판매자 정보 탭에서 `판매자 정보 더보기` 버튼이 아직 구현이 안되었음에도 불구하고 front-end 상에서 등록되어 있습니다. 

- 다음과 같이 수정
1. 기획, 디자인, 개발 이전에는 '버튼' 제거
2. 기획,디자인,개발 이후 추가.

**Comment by ywoo-park** [comment]
@wakii 일단 판매자 정보 더보기 버튼을 제거 해놓았습니다!
