### ISSUE TITLE
회원가입 전공 검색 - 추가 전공 선택시에도 아이콘 이외 영역 선택 가능하게 오류 수정

### ISSUE THREAD

**Issue by rhrhak14** [boogle-lab/boogle-issue-board#9]
회원가입 전공 검색에서 추가 전공 선택시에도 아이콘 이외 영역 선택 가능하게 오류 수정
- 현재 첫번째 전공 선택에서만 이외 영역 선택 가능
- 추가 전공에도 동일하게 적용

**Comment by ywoo-park** [comment]
2번째, 3번째 input 클릭시에도 선택 가능하도록 수정했습니다!
